name: CI

on: [push]

env:
  BRANCH: default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set BRANCH
      run: echo "${GITHUB_REF##*/}" > $BRANCH

    - name: Output BRANCH
      run:  echo "BRANCH=$BRANCH" 

    - name: Set BRANCH2 again
      run: echo "${GITHUB_REF##*/}" > $BRANCH2

    - name: Output BRANCH2
      run:  echo "BRANCH2=$BRANCH2" 
