name: CI

on: [push]

env:
  BRANCH_GLOBAL: global

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_JOB: job
    steps:
    - name: Set BRANCH_GLOBAL
      run: |
        echo "branch-${GITHUB_REF##*/}" >> $BRANCH_GLOBAL
        env | egrep BRANCH
         
    - name: Set BRANCH_JOB
      run: |
         echo "branch-${GITHUB_REF##*/}" >> $BRANCH_JOB
         env | egrep '^BRANCH'
         
    - name: Set BRANCH_STEP
      env: 
         BRANCH_STEP: step
      run: |
         echo "branch-${GITHUB_REF##*/}" >> $BRANCH_STEP
         env | egrep '^BRANCH'

    - name: Set BRANCH_LOCAL
      run: |
         export BRANCH_LOCAL="local"
         echo "branch-${GITHUB_REF##*/}" >> $BRANCH_LOCAL
         env | egrep '^BRANCH'
         
    - name: Output environment
      run:  env | egrep '^BRANCH'

