name: CI

on: [push]

env:
  BRANCH_GLOBAL: global

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_JOB: job
    steps:
    - name: Set BRANCH_GLOBAL
      run: |
        echo "BRANCH_GLOBAL=branch-${GITHUB_REF##*/}" >> $GITHUB_ENV
         
    - name: Set BRANCH_JOB
      run: |
         echo "BRANCH_JOB=branch-${GITHUB_REF##*/}" >> $GITHUB_ENV
         
    - name: Set BRANCH_STEP
      env: 
         BRANCH_STEP: step
      run: |
         echo "BRANCH_STEP=branch-${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set BRANCH_LOCAL
      run: |
         export BRANCH_LOCAL="local"
         echo "BRANCH_LOCAL=branch-${GITHUB_REF##*/}" >> $GITHUB_ENV
         
    - name: Output environment
      run:  env | egrep '^BRANCH'

